language : cpp
compiler : gcc
before_script:
  - sudo apt-get update

script : ./build.sh
env :
  matrix :
    - OS=LINUX ARCH=i686
    - OS=LINUX ARCH=x86_64
    - OS=WIN ARCH=i686
    - OS=WIN ARCH=x86_64
