language : cpp
compiler : gcc
before_script:
  - sudo apt-get update
  - sudo apt-get install qt4-dev-tools libqjson-dev
  - git submodule init && git submodule update && cd ChronoReader && git submodule init && git submodule update && cd
script : qmake Logger21.pro && make
