#############################################################################
# Makefile for building: Logger21
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Mar 8 15:01:04 2014
# Project:  Logger21.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Logger21.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQWT_DLL -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu /usr/lib/libqwt.so -lqjson -lQtWebKit -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = FenPrincipale.cpp \
		dialog.cpp \
		tablemgr.cpp \
		main.cpp \
		UI/mapsview.cpp \
		UI/boardingtable.cpp \
		InPut/serial.cpp \
		InPut/sensormanager.cpp \
		InPut/fileimportdialog.cpp \
		ChronoReader/chronoreaderwidget.cpp \
		ChronoReader/TimeCalc/timecalcs.cpp \
		ChronoReader/eventbox.cpp \
		UI/graphicview.cpp \
		InPut/cookiedecoder.cpp \
		InPut/yolodecoder.cpp \
		InPut/databasecontroller.cpp \
		InPut/sensor.cpp \
		InPut/sensorvalue.cpp moc_FenPrincipale.cpp \
		moc_dialog.cpp \
		moc_mapsview.cpp \
		moc_serial.cpp \
		moc_sensormanager.cpp \
		moc_fileimportdialog.cpp \
		moc_chronoreaderwidget.cpp \
		moc_eventbox.cpp \
		moc_graphicview.cpp \
		moc_cookiedecoder.cpp \
		moc_yolodecoder.cpp \
		moc_databasecontroller.cpp \
		qrc_res.cpp
OBJECTS       = FenPrincipale.o \
		dialog.o \
		tablemgr.o \
		main.o \
		mapsview.o \
		boardingtable.o \
		serial.o \
		sensormanager.o \
		fileimportdialog.o \
		chronoreaderwidget.o \
		timecalcs.o \
		eventbox.o \
		graphicview.o \
		cookiedecoder.o \
		yolodecoder.o \
		databasecontroller.o \
		sensor.o \
		sensorvalue.o \
		moc_FenPrincipale.o \
		moc_dialog.o \
		moc_mapsview.o \
		moc_serial.o \
		moc_sensormanager.o \
		moc_fileimportdialog.o \
		moc_chronoreaderwidget.o \
		moc_eventbox.o \
		moc_graphicview.o \
		moc_cookiedecoder.o \
		moc_yolodecoder.o \
		moc_databasecontroller.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Logger21.pro
QMAKE_TARGET  = Logger21
DESTDIR       = 
TARGET        = Logger21

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_FenPrincipale.h ui_dialog.h ui_fileimportdialog.h ui_chronoreaderwidget.h ui_eventbox.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Logger21.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Logger21.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Logger21.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Logger211.0.0 || $(MKDIR) .tmp/Logger211.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Logger211.0.0/ && $(COPY_FILE) --parents tablemgr.h FenPrincipale.h dialog.h defines.h UI/mapsview.h UI/boardingtable.h InPut/serial.h InPut/sensorvalue.h InPut/sensormanager.h InPut/sensor.h InPut/fileimportdialog.h ChronoReader/chronoreaderwidget.h ChronoReader/TimeCalc/timecalcs.h ChronoReader/eventbox.h UI/graphicview.h InPut/cookiedecoder.h InPut/yolodecoder.h InPut/databasecontroller.h .tmp/Logger211.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/Logger211.0.0/ && $(COPY_FILE) --parents FenPrincipale.cpp dialog.cpp tablemgr.cpp main.cpp UI/mapsview.cpp UI/boardingtable.cpp InPut/serial.cpp InPut/sensormanager.cpp InPut/fileimportdialog.cpp ChronoReader/chronoreaderwidget.cpp ChronoReader/TimeCalc/timecalcs.cpp ChronoReader/eventbox.cpp UI/graphicview.cpp InPut/cookiedecoder.cpp InPut/yolodecoder.cpp InPut/databasecontroller.cpp InPut/sensor.cpp InPut/sensorvalue.cpp .tmp/Logger211.0.0/ && $(COPY_FILE) --parents FenPrincipale.ui dialog.ui InPut/fileimportdialog.ui ChronoReader/chronoreaderwidget.ui ChronoReader/eventbox.ui .tmp/Logger211.0.0/ && (cd `dirname .tmp/Logger211.0.0` && $(TAR) Logger211.0.0.tar Logger211.0.0 && $(COMPRESS) Logger211.0.0.tar) && $(MOVE) `dirname .tmp/Logger211.0.0`/Logger211.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Logger211.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_FenPrincipale.cpp moc_dialog.cpp moc_mapsview.cpp moc_serial.cpp moc_sensormanager.cpp moc_fileimportdialog.cpp moc_chronoreaderwidget.cpp moc_eventbox.cpp moc_graphicview.cpp moc_cookiedecoder.cpp moc_yolodecoder.cpp moc_databasecontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FenPrincipale.cpp moc_dialog.cpp moc_mapsview.cpp moc_serial.cpp moc_sensormanager.cpp moc_fileimportdialog.cpp moc_chronoreaderwidget.cpp moc_eventbox.cpp moc_graphicview.cpp moc_cookiedecoder.cpp moc_yolodecoder.cpp moc_databasecontroller.cpp
moc_FenPrincipale.cpp: ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		FenPrincipale.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FenPrincipale.h -o moc_FenPrincipale.cpp

moc_dialog.cpp: ui_dialog.h \
		InPut/serial.h \
		defines.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_mapsview.cpp: FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		UI/mapsview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UI/mapsview.h -o moc_mapsview.cpp

moc_serial.cpp: defines.h \
		InPut/serial.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/serial.h -o moc_serial.cpp

moc_sensormanager.cpp: InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		InPut/sensormanager.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/sensormanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/sensormanager.h -o moc_sensormanager.cpp

moc_fileimportdialog.cpp: FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		ui_fileimportdialog.h \
		InPut/fileimportdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/fileimportdialog.h -o moc_fileimportdialog.cpp

moc_chronoreaderwidget.cpp: ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		ChronoReader/chronoreaderwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ChronoReader/chronoreaderwidget.h -o moc_chronoreaderwidget.cpp

moc_eventbox.cpp: ChronoReader/TimeCalc/timecalcs.h \
		ChronoReader/eventbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ChronoReader/eventbox.h -o moc_eventbox.cpp

moc_graphicview.cpp: Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		UI/mapsview.h \
		UI/graphicview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) UI/graphicview.h -o moc_graphicview.cpp

moc_cookiedecoder.cpp: defines.h \
		InPut/cookiedecoder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/cookiedecoder.h -o moc_cookiedecoder.cpp

moc_yolodecoder.cpp: InPut/yolodecoder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/yolodecoder.h -o moc_yolodecoder.cpp

moc_databasecontroller.cpp: InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/databasecontroller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InPut/databasecontroller.h -o moc_databasecontroller.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		html/maps.html \
		html/chart.html \
		js/highstock.js \
		js/exporting.js \
		js/jquery.js
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_FenPrincipale.h ui_dialog.h ui_fileimportdialog.h ui_chronoreaderwidget.h ui_eventbox.h
compiler_uic_clean:
	-$(DEL_FILE) ui_FenPrincipale.h ui_dialog.h ui_fileimportdialog.h ui_chronoreaderwidget.h ui_eventbox.h
ui_FenPrincipale.h: FenPrincipale.ui
	/usr/bin/uic-qt4 FenPrincipale.ui -o ui_FenPrincipale.h

ui_dialog.h: dialog.ui
	/usr/bin/uic-qt4 dialog.ui -o ui_dialog.h

ui_fileimportdialog.h: InPut/fileimportdialog.ui
	/usr/bin/uic-qt4 InPut/fileimportdialog.ui -o ui_fileimportdialog.h

ui_chronoreaderwidget.h: ChronoReader/chronoreaderwidget.ui
	/usr/bin/uic-qt4 ChronoReader/chronoreaderwidget.ui -o ui_chronoreaderwidget.h

ui_eventbox.h: ChronoReader/eventbox.ui
	/usr/bin/uic-qt4 ChronoReader/eventbox.ui -o ui_eventbox.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

FenPrincipale.o: FenPrincipale.cpp FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		InPut/fileimportdialog.h \
		ui_fileimportdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FenPrincipale.o FenPrincipale.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h \
		InPut/serial.h \
		defines.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

tablemgr.o: tablemgr.cpp tablemgr.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		InPut/sensor.h \
		InPut/sensormanager.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablemgr.o tablemgr.cpp

main.o: main.cpp defines.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mapsview.o: UI/mapsview.cpp UI/mapsview.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapsview.o UI/mapsview.cpp

boardingtable.o: UI/boardingtable.cpp UI/boardingtable.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boardingtable.o UI/boardingtable.cpp

serial.o: InPut/serial.cpp InPut/serialdecoder.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o InPut/serial.cpp

sensormanager.o: InPut/sensormanager.cpp InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensormanager.o InPut/sensormanager.cpp

fileimportdialog.o: InPut/fileimportdialog.cpp InPut/fileimportdialog.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		ui_fileimportdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileimportdialog.o InPut/fileimportdialog.cpp

chronoreaderwidget.o: ChronoReader/chronoreaderwidget.cpp ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		ui_chronoreaderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chronoreaderwidget.o ChronoReader/chronoreaderwidget.cpp

timecalcs.o: ChronoReader/TimeCalc/timecalcs.cpp ChronoReader/TimeCalc/timecalcs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timecalcs.o ChronoReader/TimeCalc/timecalcs.cpp

eventbox.o: ChronoReader/eventbox.cpp ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		ui_eventbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventbox.o ChronoReader/eventbox.cpp

graphicview.o: UI/graphicview.cpp UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/mapsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicview.o UI/graphicview.cpp

cookiedecoder.o: InPut/cookiedecoder.cpp InPut/cookiedecoder.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cookiedecoder.o InPut/cookiedecoder.cpp

yolodecoder.o: InPut/yolodecoder.cpp InPut/serial.h \
		defines.h \
		InPut/yolodecoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yolodecoder.o InPut/yolodecoder.cpp

databasecontroller.o: InPut/databasecontroller.cpp InPut/databasecontroller.h \
		InPut/sensormanager.h \
		InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databasecontroller.o InPut/databasecontroller.cpp

sensor.o: InPut/sensor.cpp InPut/sensor.h \
		InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		InPut/sensormanager.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensor.o InPut/sensor.cpp

sensorvalue.o: InPut/sensorvalue.cpp InPut/sensorvalue.h \
		defines.h \
		exprtk.hpp \
		InPut/sensor.h \
		InPut/sensormanager.h \
		FenPrincipale.h \
		ui_FenPrincipale.h \
		ChronoReader/chronoreaderwidget.h \
		ChronoReader/eventbox.h \
		ChronoReader/TimeCalc/timecalcs.h \
		InPut/cookiedecoder.h \
		InPut/serial.h \
		UI/boardingtable.h \
		UI/graphicview.h \
		Qwt/qwt_plot.h \
		Qwt/qwt_global.h \
		Qwt/qwt_text.h \
		Qwt/qwt_plot_dict.h \
		Qwt/qwt_plot_item.h \
		Qwt/qwt_legend_itemmanager.h \
		Qwt/qwt_scale_map.h \
		Qwt/qwt_math.h \
		Qwt/qwt_interval.h \
		Qwt/qwt_plot_curve.h \
		Qwt/qwt_plot_seriesitem.h \
		Qwt/qwt_scale_div.h \
		Qwt/qwt_series_data.h \
		Qwt/qwt_point_3d.h \
		Qwt/qwt_point_polar.h \
		Qwt/qwt_curve_fitter.h \
		Qwt/qwt_legend.h \
		Qwt/qwt_plot_zoomer.h \
		Qwt/qwt_plot_picker.h \
		Qwt/qwt_plot_canvas.h \
		Qwt/qwt_picker.h \
		Qwt/qwt_event_pattern.h \
		Qwt/qwt_scale_draw.h \
		Qwt/qwt_abstract_scale_draw.h \
		UI/mapsview.h \
		tablemgr.h \
		InPut/serialdecoder.h \
		InPut/databasecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensorvalue.o InPut/sensorvalue.cpp

moc_FenPrincipale.o: moc_FenPrincipale.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FenPrincipale.o moc_FenPrincipale.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_mapsview.o: moc_mapsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapsview.o moc_mapsview.cpp

moc_serial.o: moc_serial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serial.o moc_serial.cpp

moc_sensormanager.o: moc_sensormanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensormanager.o moc_sensormanager.cpp

moc_fileimportdialog.o: moc_fileimportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileimportdialog.o moc_fileimportdialog.cpp

moc_chronoreaderwidget.o: moc_chronoreaderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chronoreaderwidget.o moc_chronoreaderwidget.cpp

moc_eventbox.o: moc_eventbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventbox.o moc_eventbox.cpp

moc_graphicview.o: moc_graphicview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicview.o moc_graphicview.cpp

moc_cookiedecoder.o: moc_cookiedecoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cookiedecoder.o moc_cookiedecoder.cpp

moc_yolodecoder.o: moc_yolodecoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yolodecoder.o moc_yolodecoder.cpp

moc_databasecontroller.o: moc_databasecontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databasecontroller.o moc_databasecontroller.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

